package vn.vnpt.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class CauHinhThongTinDuongSuAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertCauHinhThongTinDuongSuAllPropertiesEquals(CauHinhThongTinDuongSu expected, CauHinhThongTinDuongSu actual) {
        assertCauHinhThongTinDuongSuAutoGeneratedPropertiesEquals(expected, actual);
        assertCauHinhThongTinDuongSuAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertCauHinhThongTinDuongSuAllUpdatablePropertiesEquals(
        CauHinhThongTinDuongSu expected,
        CauHinhThongTinDuongSu actual
    ) {
        assertCauHinhThongTinDuongSuUpdatableFieldsEquals(expected, actual);
        assertCauHinhThongTinDuongSuUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertCauHinhThongTinDuongSuAutoGeneratedPropertiesEquals(
        CauHinhThongTinDuongSu expected,
        CauHinhThongTinDuongSu actual
    ) {
        assertThat(expected)
            .as("Verify CauHinhThongTinDuongSu auto generated properties")
            .satisfies(e -> assertThat(e.getId()).as("check id").isEqualTo(actual.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertCauHinhThongTinDuongSuUpdatableFieldsEquals(CauHinhThongTinDuongSu expected, CauHinhThongTinDuongSu actual) {
        assertThat(expected)
            .as("Verify CauHinhThongTinDuongSu relevant properties")
            .satisfies(e -> assertThat(e.getIdCauHinh()).as("check idCauHinh").isEqualTo(actual.getIdCauHinh()))
            .satisfies(e -> assertThat(e.getNoiDung()).as("check noiDung").isEqualTo(actual.getNoiDung()))
            .satisfies(e -> assertThat(e.getJavascript()).as("check javascript").isEqualTo(actual.getJavascript()))
            .satisfies(e -> assertThat(e.getCss()).as("check css").isEqualTo(actual.getCss()))
            .satisfies(e -> assertThat(e.getIdLoaiDs()).as("check idLoaiDs").isEqualTo(actual.getIdLoaiDs()))
            .satisfies(e -> assertThat(e.getIdDonVi()).as("check idDonVi").isEqualTo(actual.getIdDonVi()))
            .satisfies(e -> assertThat(e.getTrangThai()).as("check trangThai").isEqualTo(actual.getTrangThai()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertCauHinhThongTinDuongSuUpdatableRelationshipsEquals(
        CauHinhThongTinDuongSu expected,
        CauHinhThongTinDuongSu actual
    ) {}
}
