package vn.vnpt.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class DanhMucLoaiDuongSuAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertDanhMucLoaiDuongSuAllPropertiesEquals(DanhMucLoaiDuongSu expected, DanhMucLoaiDuongSu actual) {
        assertDanhMucLoaiDuongSuAutoGeneratedPropertiesEquals(expected, actual);
        assertDanhMucLoaiDuongSuAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertDanhMucLoaiDuongSuAllUpdatablePropertiesEquals(DanhMucLoaiDuongSu expected, DanhMucLoaiDuongSu actual) {
        assertDanhMucLoaiDuongSuUpdatableFieldsEquals(expected, actual);
        assertDanhMucLoaiDuongSuUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertDanhMucLoaiDuongSuAutoGeneratedPropertiesEquals(DanhMucLoaiDuongSu expected, DanhMucLoaiDuongSu actual) {
        assertThat(expected)
            .as("Verify DanhMucLoaiDuongSu auto generated properties")
            .satisfies(e -> assertThat(e.getId()).as("check id").isEqualTo(actual.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertDanhMucLoaiDuongSuUpdatableFieldsEquals(DanhMucLoaiDuongSu expected, DanhMucLoaiDuongSu actual) {
        assertThat(expected)
            .as("Verify DanhMucLoaiDuongSu relevant properties")
            .satisfies(e -> assertThat(e.getIdLoaiDs()).as("check idLoaiDs").isEqualTo(actual.getIdLoaiDs()))
            .satisfies(e -> assertThat(e.getDienGiai()).as("check dienGiai").isEqualTo(actual.getDienGiai()))
            .satisfies(e -> assertThat(e.getTrangThai()).as("check trangThai").isEqualTo(actual.getTrangThai()))
            .satisfies(e -> assertThat(e.getStrSearch()).as("check strSearch").isEqualTo(actual.getStrSearch()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertDanhMucLoaiDuongSuUpdatableRelationshipsEquals(DanhMucLoaiDuongSu expected, DanhMucLoaiDuongSu actual) {}
}
