package vn.vnpt.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class DanhMucTinhTrangHonNhanAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertDanhMucTinhTrangHonNhanAllPropertiesEquals(DanhMucTinhTrangHonNhan expected, DanhMucTinhTrangHonNhan actual) {
        assertDanhMucTinhTrangHonNhanAutoGeneratedPropertiesEquals(expected, actual);
        assertDanhMucTinhTrangHonNhanAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertDanhMucTinhTrangHonNhanAllUpdatablePropertiesEquals(
        DanhMucTinhTrangHonNhan expected,
        DanhMucTinhTrangHonNhan actual
    ) {
        assertDanhMucTinhTrangHonNhanUpdatableFieldsEquals(expected, actual);
        assertDanhMucTinhTrangHonNhanUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertDanhMucTinhTrangHonNhanAutoGeneratedPropertiesEquals(
        DanhMucTinhTrangHonNhan expected,
        DanhMucTinhTrangHonNhan actual
    ) {
        assertThat(expected)
            .as("Verify DanhMucTinhTrangHonNhan auto generated properties")
            .satisfies(e -> assertThat(e.getId()).as("check id").isEqualTo(actual.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertDanhMucTinhTrangHonNhanUpdatableFieldsEquals(
        DanhMucTinhTrangHonNhan expected,
        DanhMucTinhTrangHonNhan actual
    ) {
        assertThat(expected)
            .as("Verify DanhMucTinhTrangHonNhan relevant properties")
            .satisfies(e -> assertThat(e.getIdTinhTrang()).as("check idTinhTrang").isEqualTo(actual.getIdTinhTrang()))
            .satisfies(e -> assertThat(e.getDienGiai()).as("check dienGiai").isEqualTo(actual.getDienGiai()))
            .satisfies(e -> assertThat(e.getTrangThai()).as("check trangThai").isEqualTo(actual.getTrangThai()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertDanhMucTinhTrangHonNhanUpdatableRelationshipsEquals(
        DanhMucTinhTrangHonNhan expected,
        DanhMucTinhTrangHonNhan actual
    ) {}
}
